services:
  - type: web
    name: easyaid
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn EasyAid.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: easyaid-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DISABLE_COLLECTSTATIC
        value: "0"
databases:
  - name: easyaid-db
    plan: free